services:
  backend:
    build: ./backend
    ports:
      - "5555:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:strongpass@postgres:5432/financeapp
      - PYTHONPATH=/app
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - finance-net

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strongpass
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - finance-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://192.168.0.110:5555/api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://192.168.0.110:5555/api/v1
    networks:
      - finance-net

networks:
  finance-net:

volumes:
  pg_data:
