services:
  backend:
    build: ./backend
    ports:
      - "5555:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=financeapp
      - PYTHONPATH=/app
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - finance-net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - finance-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://192.168.0.110:5555/api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://192.168.0.110:5555/api/v1
    networks:
      - finance-net

volumes:
  mongo_data:

networks:
  finance-net:
